First try

In [1]:
from numpy import exp, array, random, dot

#Definining a class for model
class sequential():

    def __init__(self):

        #initialing the seed
        random.seed(1)
        self.weights = 2 * random.random((3, 1)) - 1 #Initializing weights

    def sigmoid(self, x):
        return 1 / (1 + exp(-x))#Sigmoid function

    def calcSlope(self, x):
        return x * (1 - x) #Slope 

    def predict(self, X):
        return self.sigmoid(dot(X, self.weights)) #Activation

    def predict_class(self, X):
        if(self.predict(X)>0.5):
          return 1
        else:
          return 0  
    
    def train(self, X, y, epochs):

        for i in range(epochs): #Iterations aka epochs

            y_pred = self.predict(X) # label predicted by network, (single neuron)

            error = y - y_pred # Calculating error

            weight_update = dot(X.T, error * self.calcSlope(y_pred)) 

            # Updating weights on the basis of slope, 
            # each weight gets updated on the basis of its contribution in error

            self.weights += weight_update

#Dataset
X = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
y = array([[0, 1, 1, 0]]).T


print ('\n Input:')
print(X)

print ('\n Actual Output:')
print(y)

model = sequential() #Instantiating model

print ("\nWeights before training: ")
print (model.weights)

#Training on 10000 epochs
model.train(X, y, 5000)

print ("\nWeights after training: ")
print (model.weights)

print ('\n\n*************************\nPrediction:')

print ("\n\nTesting on [1, 0, 0]:")
print (model.predict_class(array([1, 0, 0]))) 

print ("\n\nTesting on [0, 0, 1]:")
print (model.predict_class(array([0, 0, 1]))) 


 Input:
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]

 Actual Output:
[[0]
 [1]
 [1]
 [0]]

Weights before training: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

Weights after training: 
[[ 8.95950703]
 [-0.20975775]
 [-4.27128529]]


*************************
Prediction:


Testing on [1, 0, 0]:
1


Testing on [0, 0, 1]:
0


Second Try

In [0]:
import numpy as np

X=np.array([ 
             [1,0,1,0],
             [1,0,1,1],
             [0,1,0,1]
           ])

y=np.array([[1],[1],[0]])


In [3]:
class sequential2():

    def __init__(self):
      # initializing the variables
        # self.epoch=5000 
        self.lr=0.1 

        # initializing weight and bias
        self.w1=np.random.uniform(size=(X.shape[1],3))
        self.b1=np.random.uniform(size=(1,3))
        self.w2=np.random.uniform(size=(3,1))
        self.b2=np.random.uniform(size=(1,1))

        self.z1=0
        self.z2=0
        self.a1=0
        self.a2=0
        print('\nWeights before training:\nwh:\n{} \nwout: \n{} \n'.format(self.w1,self.w2))



    def sigmoid (self,x):
        return 1/(1 + np.exp(-x))

    def calc_slope(self,x):
        return x * (1 - x)

    def predict(self,X):
        #Forward prop
        self.z1=np.dot(X,self.w1)
        self.z1=self.z1 + self.b1
        self.a1 = self.sigmoid(self.z1)#activation

        self.z2=np.dot(self.a1,self.w2)
        self.z2= self.z2+ self.b2
        self.a2 =self.sigmoid(self.z2)
        return self.a2

    def predict_class(self, X):
        if(self.predict(X)>0.5):
          return 1
        else:
          return 0  

    def train(self,X, epoch):

      # training the model
        for i in range(epoch):

            #forward propagation
            self.predict(X)

            #Backpropagation
            
            #calculating error
            E = y-self.a2

            #calculating slopes
            l2 = self.calc_slope(self.a2)
            l1 = self.calc_slope(self.a1)

            d2 = E * l2
            e1 = d2.dot(self.w2.T)
            d1 = e1 * l1

            #Updation of weights and biases with respect to error and learning rate
            # T = transpose
            self.w2 += self.a1.T.dot(d2) *self.lr
            self.b2 += np.sum(d2, axis=0,keepdims=True) *self.lr
            self.w1 += X.T.dot(d1) *self.lr
            self.b1 += np.sum(d1, axis=0,keepdims=True) *self.lr

        print('\nWeights after training:\nwh: \n{}\nwout: \n{}'.format(self.w1,self.w2))

print ('\n Input:')
print(X)

print ('\n Actual Output:')
print(y)

model = sequential2()
model.train(X,5000)
print ('\n\n*************************\nPrediction:')

print(model.predict_class([1,0,1,0]))
print(model.predict_class([1,0,1,1]))
print(model.predict_class([0,1,0,1]))


 Input:
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]

 Actual Output:
[[1]
 [1]
 [0]]

Weights before training:
wh:
[[0.30233257 0.14675589 0.09233859]
 [0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]
 [0.20445225 0.87811744 0.02738759]] 
wout: 
[[0.14038694]
 [0.19810149]
 [0.80074457]] 


Weights after training:
wh: 
[[ 0.12834561 -1.41338192  1.6931045 ]
 [ 0.41635588  1.39998964 -1.86176229]
 [ 0.36482977 -1.1409433   2.28598541]
 [ 0.32695637  0.86934366 -1.0568335 ]]
wout: 
[[-0.38489259]
 [-3.07912606]
 [ 4.84661501]]


*************************
Prediction:
1
1
0


Try 3 (XOR function)

In [4]:
import numpy as np
def sigmoid (x):
    return 1/(1 + np.exp(-x))
 
#Input data
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([ [0],   [1],   [1],   [0]])

epochs = 50000 #was giving poor accuracy on smaller epochs
LR = .3 # learning rate

#Weight initialization 
w1 = np.random.uniform(size=(2, 3))
w2 = np.random.uniform(size=(3, 1))

print ('\n Input:')
print(X)

print ('\n Actual Output:')
print(y)

print('\nWeights before training:\nwh:\n{} \nwout: \n{} \n'.format(w1,w2))

for i in range(epochs):
 
    # Forward propagation
    a = sigmoid(np.dot(X, w1))
    y_pred = np.dot(a, w2)
    
    # Calculate error
    e = y - y_pred
    
    # if i % 10000 == 0:
    #     print(f'Error: {sum(e)}')

    # Backward Propagation 
    #Weight updation
    d2 = e * LR
    w2 += a.T.dot(d2)
    d1 = d2.dot(w2.T) * sigmoid(a)
    w1 += X.T.dot(d1)


print('\nWeights after training:\nwh: \n{}\nwout: \n{}'.format(w1,w2))



 Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

 Actual Output:
[[0]
 [1]
 [1]
 [0]]

Weights before training:
wh:
[[0.31342418 0.69232262 0.87638915]
 [0.89460666 0.08504421 0.03905478]] 
wout: 
[[0.16983042]
 [0.8781425 ]
 [0.09834683]] 


Weights after training:
wh: 
[[ 3.03000179e-01 -4.24453501e+02  4.25631797e+02]
 [ 1.18593982e+00  4.24350419e+02 -4.25734879e+02]]
wout: 
[[3.60822483e-15]
 [5.12865101e-01]
 [5.12865101e-01]]


In [8]:

a = sigmoid(np.dot([1,1], w1))
np.dot(a, w2)# hence 0

array([0.4864549])